name: Upload Image

on:
  push:
    branches:
      - main  # substitua pela sua branch principal

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Upload image to GitHub Pages
        run: |
          mkdir -p public/images
          cp -R images/* public/images/
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add public/images
          git commit -m "Uploaded new image"
          git push
